services:
  cookies_test:
    container_name: cookies_test
    hostname: cookies_test
    restart: always
    build:
      context: ./
    ports:
      - "8081:8081"
    expose:
      - 8081
    env_file:
      - .env
